services:
  backend-for-frontend:
    build:
      context: services/backend-for-frontend-python
      dockerfile: Dockerfile
    image: backend-for-frontend-python:latest
    ports:
      - "10115:10115"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=backend-for-frontend

  image-picker:
    build:
      context: services/image-picker-go
      dockerfile: Dockerfile
    image: image-picker-go:latest
    ports:
      - "10116:10116" # the outer ports can't be the same
    environment:
      - BUCKET_NAME
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=image-picker-go

  meminator:
    build:
      context: services/meminator-python
      dockerfile: Dockerfile
    image: meminator-python:latest
    ports:
      - "10117:10117" # they can't be the same
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=meminator-python

  phrase-picker:
    build:
      context: services/phrase-picker-go
      dockerfile: Dockerfile
    image: phrase-picker-go:latest
    ports:
      - "10118:10118" # the outer ports can't be the same
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=phrase-picker-go

  web:
    build:
      context: services/web
      dockerfile: Dockerfile
      args:
        HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
    image: web:latest
    # volumes: # uncomment this for faster development on the frontend
    #   - ./services/web/dist:/usr/share/nginx/html # Mount directory containing static files -- only do this for development
    ports:
      - "10114:10114" # Expose port 10114 for Nginx
    depends_on:
      backend-for-frontend:
        condition: service_started
      image-picker:
        condition: service_started
      meminator:
        condition: service_started
      phrase-picker:
        condition: service_started    
